services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLAMA_API_URL=http://ollama:11434/api/generate
      - LLAMA_MODEL=llama3:8b
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: /bin/sh
    command: -c "ollama serve && ollama pull llama3:8b"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  ollama-data: